from setuptools import setup

setup(name='pytest-caseconductor',
      version='0.1',
      description='Case Conductor plugin for py.test.',
      author='Dave Hunt',
      author_email='dhunt@mozilla.com',
      url='https://github.com/davehunt/pytest-caseconductor',
      py_modules=['pytest_caseconductor'],
      install_requires=['pytest>=2.2.3'],
      entry_points={'pytest11': ['pytest_caseconductor = pytest_caseconductor']},
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='py.test pytest caseconductor case conductor test management mozilla',
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
                   'Operating System :: POSIX',
                   'Operating System :: Microsoft :: Windows',
                   'Operating System :: MacOS :: MacOS X',
                   'Topic :: Software Development :: Quality Assurance',
                   'Topic :: Software Development :: Testing',
                   'Topic :: Utilities',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 2.6',
                   'Programming Language :: Python :: 2.7'])
